### ISSUE TITLE
Bad position

### ISSUE THREAD

**Issue by mstrop** [PieceMaker/max-inscribed-circle#17]
Probably I am using the library in wrong way, but I get the circle at wrong position. My code is:

```
var coords = [
    [49.0138, 15],
    [49.0138, 15.0167],
    [49.0153, 15.0167]
];

var polygon = {
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [coords]
     },
     "properties": {
        "id": 1
     }
};

console.log(maxInscribedCircle(polygon, 7));

```
 It gives me this response:

```
{
  geometry: {
    coordinates: [49.0143, 15.011133333333333],
    type: "Point"
  },
  properties: {
    radius: 0.0004823742421792941,
    units: "degrees"
  }
}

```
It is possible to see the result here - [https://i.stack.imgur.com/by9vx.jpg](url). The circle should be more on east. 

How to correctly represent radius? It states units: degrees. Lat and lon degrees are different, so I am not sure how to convert it to meters.

**Comment by PieceMaker** [comment]
The issue does not appear to lie in your code, but rather the library itself. In the README, the third bullet under the Future section is meant to address this. The `sites` method of the `GeoJSONUtils ` class generates vertices from which to build the Voronoi approximation to the medial axis. However, this is hard-coded to only ever choose the midpoint of each line segment defining a GeoJSON polygon. If this function accepted an argument specifying how many vertices to split each segment into, then a better approximation of the medial axis could be achieved, thereby resulting in a better center for the max inscribed circle (at the cost of more compute time).

I never implemented this feature since the function gave sufficient results for my work, but now that I know someone else is using it and it would be beneficial to them I will work on adding this functionality over the next couple of weeks.

Thanks for reporting this issue!

**Comment by PieceMaker** [comment]
I think the changes in branch "jadams-convert-to-options" should provide functionality that will result in the centroid you are looking for. I need to do a little more checking before I publish it, but I'll publish them to version 2.0.0 when I'm done.
